### ISSUE TITLE
Alert pops in off screen

### ISSUE THREAD

**Issue by buitim** [sellenth/Link2Phone#1]
Howdy.

So this happens. Plz fix k thx.

![image](https://user-images.githubusercontent.com/29244321/94090760-466da280-fdcb-11ea-87ab-cb82c101acbc.png)

~~I dig the shine effect tho~~

**Comment by sellenth** [comment]
Dang, you are good at finding bugs! Sadly the styling of an alert is entirely controlled by the web browser and the alert position may be influenced by your window manager. I'll bring this issue up with the boys over at Google HQ, hopefully they'll get on it!

Below is how the alert is supposed to render. 

![unbug](https://user-images.githubusercontent.com/32111548/94199142-360e0400-fe6d-11ea-8008-03480821e2af.png)
